# Generated by Django 5.1.1 on 2024-09-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
