# Generated by Django 5.1.1 on 2024-09-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.CharField(default='', max_length=20),
        ),
    ]
